### ISSUE TITLE
PHP Exception  -  libraries/src/MVC/View/HtmlView.php Line: 712

### ISSUE THREAD

**Issue by ssnobben** [widgetfactory/jce#99]
Hi I got this error message coming from Admin Tools Pro about JCE.

Any tips to close it appreciated..
-----------------------------------------------------------------------

A PHP Exception occurred on your site. Here you can find the stack trace:

Exception Type: Exception
File: /home/sflnojcm/public_html/libraries/src/MVC/View/HtmlView.php
Line: 712
Message: Layout default not found.

#0 /home/sflnojcm/public_html/libraries/src/MVC/View/HtmlView.php(230): Joomla\CMS\MVC\View\HtmlView->loadTemplate()
#1 /home/sflnojcm/public_html/administrator/components/com_jce/views/cpanel/view.html.php(39): Joomla\CMS\MVC\View\HtmlView->display()
#2 /home/sflnojcm/public_html/administrator/components/com_jce/controller.php(130): JceViewCpanel->display()
#3 /home/sflnojcm/public_html/libraries/src/MVC/Controller/BaseController.php(702): JceController->display()
#4 /home/sflnojcm/public_html/administrator/components/com_jce/jce.php(35): Joomla\CMS\MVC\Controller\BaseController->execute()
#5 /home/sflnojcm/public_html/components/com_jce/jce.php(13): require_once('/home/sflnojcm/...')
#6 /home/sflnojcm/public_html/libraries/src/Component/ComponentHelper.php(402): require_once('/home/sflnojcm/...')
#7 /home/sflnojcm/public_html/libraries/src/Component/ComponentHelper.php(377): Joomla\CMS\Component\ComponentHelper::executeComponent()
#8 /home/sflnojcm/public_html/libraries/src/Application/SiteApplication.php(194): Joomla\CMS\Component\ComponentHelper::renderComponent()
#9 /home/sflnojcm/public_html/libraries/src/Application/SiteApplication.php(233): Joomla\CMS\Application\SiteApplication->dispatch()
#10 /home/sflnojcm/public_html/libraries/src/Application/CMSApplication.php(225): Joomla\CMS\Application\SiteApplication->doExecute()
#11 /home/sflnojcm/public_html/index.php(49): Joomla\CMS\Application\CMSApplication->execute()
#12 {main}

Request information
GET variables

Array
(
)

POST variables

Array
(
)

COOKIE variables

Array
(
)

REQUEST variables

Array
(
    [language] => en-GB
    [option] => com_jce
    [Itemid] => 
    [lang] => en-GB
    [helix_id] => 9
)

SERVER variables

Array
(
    [PATH] => /usr/local/bin:/usr/bin:/bin
    [TEMP] => /tmp
    [TMP] => /tmp
    [TMPDIR] => /tmp
    [PWD] => /
    [HTTP_ACCEPT] => */*
    [HTTP_ACCEPT_ENCODING] => gzip, deflate, br
    [HTTP_ACCEPT_LANGUAGE] => sv-SE,sv;q=0.8,en-US;q=0.5,en;q=0.3
    [HTTP_CONNECTION] => close
    [CONTENT_LENGTH] => 0
    [HTTP_HOST] => www.site.com
    [HTTP_USER_AGENT] => Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0
    [HTTP_X_FORWARDED_FOR] =>  
    [HTTP_X_REAL_IP] =>  
    [HTTP_X_FORWARDED_PROTO] => https
    [HTTP_X_FORWARDED_SSL] => off
    [HTTP_X_FORWARDED_PORT] => 443
    [HTTP_DNT] => 1
    [HTTP_SEC_FETCH_DEST] => empty
    [HTTP_SEC_FETCH_MODE] => no-cors
    [HTTP_SEC_FETCH_SITE] => same-origin
    [HTTP_BN_CLIENT_PORT] => 60384
    [HTTP_X_HTTPS] => 1
    [REDIRECT_UNIQUE_ID] => YTDmohfGDrFJuGkE6vaGGAAAAFM
    [REDIRECT_GEOIP_ADDR] =>  
    [REDIRECT_GEOIP_CONTINENT_CODE] =>  
    [REDIRECT_GEOIP_COUNTRY_CODE] =>  
    [REDIRECT_GEOIP_COUNTRY_NAME] =>  
    [REDIRECT_GEOIP_DMA_CODE] => 0
    [REDIRECT_GEOIP_AREA_CODE] => 0
    [REDIRECT_GEOIP_LATITUDE] => 59.324699
    [REDIRECT_GEOIP_LONGITUDE] => 18.056000
    [REDIRECT_SCRIPT_URL] => /component/jce/
    [REDIRECT_SCRIPT_URI] => https://www.site.com/component/jce/
    [REDIRECT_HTTP_AUTHORIZATION] => 
    [REDIRECT_HTTPS] => on
    [REDIRECT_STATUS] => 200
    [UNIQUE_ID] => YTDmohfGDrFJuGkE6vaGGAAAAFM
    [GEOIP_ADDR] =>  
    [GEOIP_CONTINENT_CODE] =>  
    [GEOIP_COUNTRY_CODE] =>  
    [GEOIP_COUNTRY_NAME] =>  
    [GEOIP_DMA_CODE] => 0
    [GEOIP_AREA_CODE] => 0
    [GEOIP_LATITUDE] => 59.324699
    [GEOIP_LONGITUDE] => 18.056000
    [SCRIPT_URL] => /component/jce/
    [SCRIPT_URI] => https://www.site.com/component/jce/
    [HTTPS] => on
    [SERVER_SIGNATURE] => 
    [SERVER_SOFTWARE] => Apache
    [SERVER_NAME] => www.site.com
    [SERVER_ADDR] =>  
    [SERVER_PORT] => 443
    [REMOTE_ADDR] =>  
    [DOCUMENT_ROOT] => /home/sflnojcm/public_html
    [REQUEST_SCHEME] => https
    [CONTEXT_PREFIX] => 
    [CONTEXT_DOCUMENT_ROOT] => /home/sflnojcm/public_html
    [SERVER_ADMIN] => webmaster@site.com
    [SCRIPT_FILENAME] => /home/sflnojcm/public_html/index.php
    [REMOTE_PORT] => 57439
    [REDIRECT_URL] => /component/jce/
    [SERVER_PROTOCOL] => HTTP/1.1
    [REQUEST_METHOD] => GET
    [QUERY_STRING] => 
    [REQUEST_URI] => /component/jce/
    [SCRIPT_NAME] => /index.php
    [PHP_SELF] => /index.php
    [REQUEST_TIME_FLOAT] => 1630594722.5265
    [REQUEST_TIME] => 1630594722
)

**Comment by ryandemmer** [comment]
I'm not seeing this in any tests. Please try a re-install.
